apiVersion: apps/v1
kind: Deployment
metadata:
  name: challenge-day-96
spec:
  replicas: 3
  selector:
    matchLabels:
      app: challenge-day-96
  template:
    metadata:
      labels:
        app: challenge-day-96
    spec:
      containers:
      - name: challenge-day-96
        image: renanipxx/challenge-day-96:latest
        ports:
        - containerPort: 3000
